[package]
name = "FunSnakeConsole"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = "0.29.0"
ratatui = "0.30.2"
tokio = { version = "1.53.1", features = ["rt", "rt-multi-thread", "macros", "time"] }
config = "0.15.14"
serde = { version = "1.0.229", features = ["derive"] }
thiserror = "2.0.20"
fixed-capacity-vec = "1.0.1"
chrono = "0.4.45"
once_cell = "1.21.4"
rand = "0.8"
serde_json = "1.0.151"
